name: cgen
description: CLI to generate a number, date, string or duration column in a CSV, TSV, etc.
version: 1.5.1
homepage: https://github.com/cgrep-tool/cgen
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

executables:
  cgen:

dependencies:
  args:
  duration: ^2.0.8

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
