name: cgen
description: Generates
version: 1.5.1
# homepage: https://www.example.com
# author: Issac <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

executables:
  cgen:

dependencies:
  args:
  duration:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
